"""Derive a small, connected driving network from the atlas's generalized road paths.

Run after build-delivery-map.py:
node --input-type=module -e "import {DELIVERY_MAP} from './src/content/deliveryMap.ts'; console.log(JSON.stringify(DELIVERY_MAP))" > /tmp/delivery-map.json
python3 scripts/build-delivery-roads.py /tmp/delivery-map.json

This is an illustrative journey, not a navigation or delivery-time service.
"""
import collections
import json
import math
import re
import sys
from pathlib import Path


def paths(svg):
    return [[tuple(map(float, pair)) for pair in re.findall(r"(-?[\d.]+),(-?[\d.]+)", line)]
            for line in svg.split("M")[1:]]


def build(source):
    data = json.loads(Path(source).read_text())
    rings = paths(next(c["outline"] for c in data["countries"] if c["id"] == "DEU"))
    rings = [(ring, (min(x for x, y in ring), min(y for x, y in ring),
                     max(x for x, y in ring), max(y for x, y in ring))) for ring in rings]

    def inside(point):
        x, y = point
        hit = False
        for ring, bounds in rings:
            if not (bounds[0] <= x <= bounds[2] and bounds[1] <= y <= bounds[3]):
                continue
            for a, b in zip(ring, ring[1:] + ring[:1]):
                if (a[1] > y) != (b[1] > y) and x < (b[0] - a[0]) * (y - a[1]) / (b[1] - a[1]) + a[0]:
                    hit = not hit
        return hit

    nodes, lookup, edges = [], {}, set()

    def node(point):
        key = (round(point[0] * 2), round(point[1] * 2))
        if key not in lookup:
            lookup[key] = len(nodes)
            nodes.append(point)
        return lookup[key]

    def connect(a, b):
        if a != b:
            edges.add(tuple(sorted((a, b))))

    for svg in data["roads"].values():
        for line in paths(svg):
            for a, b in zip(line, line[1:]):
                # Sample the entire segment; do not shortcut across neighbouring countries.
                samples = max(2, math.ceil(math.dist(a, b) / 2))
                if all(inside((a[0] + (b[0] - a[0]) * i / samples,
                               a[1] + (b[1] - a[1]) * i / samples)) for i in range(samples + 1)):
                    connect(node(a), node(b))
    # Natural Earth's individually simplified polylines have tiny junction gaps.
    # Connect neighbouring vertices within 2 SVG units (~2.8 km at this map scale).
    cells = collections.defaultdict(list)
    for i, point in enumerate(nodes):
        cells[(int(point[0] / 2), int(point[1] / 2))].append(i)
    for i, point in enumerate(nodes):
        cell = (int(point[0] / 2), int(point[1] / 2))
        for dx in [-1, 0, 1]:
            for dy in [-1, 0, 1]:
                for j in cells[(cell[0] + dx, cell[1] + dy)]:
                    other = nodes[j]
                    if j > i and math.dist(point, other) <= 2 and inside(((point[0] + other[0]) / 2, (point[1] + other[1]) / 2)):
                        connect(i, j)
    adjacency = [set() for _ in nodes]
    for a, b in edges:
        adjacency[a].add(b)
        adjacency[b].add(a)
    start = min(range(len(nodes)), key=lambda i: math.dist(nodes[i], data["hamburg"]))
    connected, stack = set(), [start]
    while stack:
        item = stack.pop()
        if item in connected:
            continue
        connected.add(item)
        stack.extend(adjacency[item] - connected)
    ordered = sorted(connected)
    index = {old: new for new, old in enumerate(ordered)}
    result = {"points": [nodes[i] for i in ordered],
              "edges": [[index[a], index[b]] for a, b in sorted(edges) if a in connected and b in connected]}
    output = Path(__file__).resolve().parent.parent / "src/content/deliveryRoads.ts"
    output.write_text("// Generated by scripts/build-delivery-roads.py. Natural Earth, public domain.\n"
                      + "export const DELIVERY_ROADS = " + json.dumps(result, separators=(",", ":")) + ";\n")
    print(f"{len(result['points'])} points, {len(result['edges'])} connections, {output.stat().st_size:,} bytes")


if __name__ == "__main__":
    build(sys.argv[1])
