"""
Builds src/content/originsMap.ts: the land of the Origins map as a grid of tones.

The map is drawn on the page as an engraving, one vertical stroke per cell, so the site never
loads a geography library or a map tile. This script runs only when the framing changes.

Source: Natural Earth 1:50m land (public domain), via the world-atlas TopoJSON package.

    curl -sL https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json -o /tmp/land-50m.json
    python3 scripts/build-origins-map.py /tmp/land-50m.json

Requires Pillow.
"""

import json
import math
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFilter

# Framing: from the Atlantic edge of Europe to eastern India, Hamburg to the Indian Ocean.
LON_MIN, LON_MAX = -12.0, 98.0
LAT_MIN, LAT_MAX = 6.0, 62.0
# Longitude is compressed by cos(40°) so the crop reads like a familiar map.
COLS = 200
ROWS = round(COLS * (LAT_MAX - LAT_MIN) / ((LON_MAX - LON_MIN) * math.cos(math.radians(40))))
SUPERSAMPLE = 6


def decode_arcs(topology):
    scale_x, scale_y = topology["transform"]["scale"]
    shift_x, shift_y = topology["transform"]["translate"]
    arcs = []
    for arc in topology["arcs"]:
        x = y = 0
        points = []
        for dx, dy in arc:
            x += dx
            y += dy
            points.append((x * scale_x + shift_x, y * scale_y + shift_y))
        arcs.append(points)
    return arcs


def ring(arcs, indices):
    points = []
    for index in indices:
        arc = arcs[index] if index >= 0 else list(reversed(arcs[~index]))
        points.extend(arc if not points else arc[1:])
    return points


def polygons(topology):
    arcs = decode_arcs(topology)
    for geometry in topology["objects"]["land"]["geometries"]:
        shapes = geometry["arcs"] if geometry["type"] == "MultiPolygon" else [geometry["arcs"]]
        for shape in shapes:
            yield [ring(arcs, indices) for indices in shape]


def to_pixel(lon, lat, width, height):
    x = (lon - LON_MIN) / (LON_MAX - LON_MIN) * width
    y = (LAT_MAX - lat) / (LAT_MAX - LAT_MIN) * height
    return x, y


def main(source):
    topology = json.loads(Path(source).read_text())
    width, height = COLS * SUPERSAMPLE, ROWS * SUPERSAMPLE
    image = Image.new("L", (width, height), 0)
    draw = ImageDraw.Draw(image)
    for shape in polygons(topology):
        outer, *holes = shape
        draw.polygon([to_pixel(lon, lat, width, height) for lon, lat in outer], fill=255)
        for hole in holes:
            draw.polygon([to_pixel(lon, lat, width, height) for lon, lat in hole], fill=0)
    coverage = image.resize((COLS, ROWS), Image.BOX)
    # Interior land is shaded deeper than the coast, so the engraving has relief, not a flat fill.
    depth = coverage.filter(ImageFilter.GaussianBlur(3))
    tones = []
    for y in range(ROWS):
        row = []
        for x in range(COLS):
            land = coverage.getpixel((x, y)) / 255
            if land < 0.35:
                row.append("0")
                continue
            inland = depth.getpixel((x, y)) / 255
            row.append(str(1 + min(3, int(inland * 3.999))))
        tones.append("".join(row))
    out = Path(__file__).resolve().parent.parent / "src/content/originsMap.ts"
    out.write_text(
        "/* Generated by scripts/build-origins-map.py from Natural Earth (public domain). */\n"
        "/* Do not edit by hand: change the framing in the script and run it again. */\n\n"
        "/** Land of the Origins map: one character per cell, 0 sea, 1 coast to 4 deep inland. */\n"
        "export const ORIGINS_MAP = {\n"
        f"  cols: {COLS},\n  rows: {ROWS},\n"
        f"  lonMin: {LON_MIN},\n  lonMax: {LON_MAX},\n  latMin: {LAT_MIN},\n  latMax: {LAT_MAX},\n"
        "  tones: [\n" + "".join(f'    "{row}",\n' for row in tones) + "  ],\n"
        "} as const;\n"
    )
    print(f"{COLS}×{ROWS} cells → {out}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "/tmp/land-50m.json")
